# Generated by Django 5.2.4 on 2025-08-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('l_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('age', models.IntegerField(verbose_name='العمر')),
                ('subject', models.CharField(max_length=100, verbose_name='المادة التي يدرسها')),
                ('years_of_experience', models.IntegerField(verbose_name='سنوات الخبرة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط حاليًا')),
            ],
            options={
                'verbose_name': 'معلم',
                'verbose_name_plural': 'معلمون',
                'ordering': ['l_name', 'f_name'],
            },
        ),
    ]
