# Generated by Django 5.2.4 on 2025-08-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('gpa', models.FloatField(default=0.0)),
                ('level', models.CharField(default='1', max_length=50)),
                ('status', models.CharField(default='نشط', max_length=50)),
                ('report', models.TextField(blank=True, default='')),
            ],
        ),
    ]
